### ISSUE TITLE
imgs

### ISSUE THREAD

**Issue by swyxio** [sw-yx/svelte-zen-garden#1]
![sveltezen](https://user-images.githubusercontent.com/6764957/73112468-73845100-3edc-11ea-978a-74bb9537833a.gif)

**Comment by swyxio** [comment]
![sveltezen](https://user-images.githubusercontent.com/6764957/73115075-7f2d4300-3eef-11ea-9c28-d499b7fbb4c1.gif)

**Comment by bwaidelich** [comment]
Hi,

if this is about the missing icons inside the editor. Those come from the `codicon.ttf` font that's shipped with the monaco editor. With
```css
@font-face {
	font-family: "codicon";
	src: url(./codicon.ttf) format("truetype");
}
```

I got those to work.

But this issue might be about something completely unrelated :)
